// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"userId"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	IsRevoked bool      `json:"isRevoked"`
}

type Run struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	DockerImage   string         `json:"dockerImage"`
	Mounts        string         `json:"mounts"`
	Parameters    string         `json:"parameters"`
	Data          string         `json:"data"`
	CreatedAt     time.Time      `json:"createdAt"`
	StartedAt     sql.NullTime   `json:"startedAt"`
	FinishedAt    sql.NullTime   `json:"finishedAt"`
	Status        string         `json:"status"`
	HasErrored    bool           `json:"hasErrored"`
	ErrorMessage  sql.NullString `json:"errorMessage"`
	UserID        string         `json:"userId"`
	GotapMetadata sql.NullString `json:"gotapMetadata"`
}

type User struct {
	ID           string       `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"passwordHash"`
	IsAdmin      bool         `json:"isAdmin"`
	CreatedAt    time.Time    `json:"createdAt"`
	LastLogin    sql.NullTime `json:"lastLogin"`
}
